export const usersArray = [
    // User 1
    {
        userDoc: {
            phone: "0541",
            firebase_id: "string",
            notification_permission: false,
            notification_token: "string",
            insta: {
                last_scrape: new Date(),
                id: "string",
                access_token: "string",
                username: "username1",
                full_name: "igFullName1",
                biography: "user1' biography",
                profile_pic:
                    "https://images.pexels.com/photos/3741382/pexels-photo-3741382.jpeg?auto=compress&cs=tinysrgb&w=600",
                followers: 11,
                following: 11,
                post_number: 11,
                average_like: 11,
                shared_posts: [
                    {
                        media_url: "string",
                        like_count: 22,
                        comment_count: 22,
                        // description: String,
                        // location: {
                        //     name: String,
                        //     address: String,
                        //     city: String,
                        //     lng: Number,
                        //     lat: Number,
                        // },
                        face_details: "any",
                        moderation_labels: "any",
                    },
                ],
                keywords: "any",
            },
            tiktok: {
                tiktok_last_scrape: new Date(),
                // tiktok_average_like: Number,
                // tiktok_engagement_rate: Number,
                tiktok_access_token: "string",
                tiktok_refresh_token: "string",
                open_id: "string",
                refresh_expires_in: "string",
                log_id: "string",
                union_id: "string",
                username: "tiktokUsername1",
                last_scrape: new Date(),
                followers: 11,
                following: 11,
                hearts: 11,
                country: "string",
                videos: [
                    {
                        like_count: 22,
                        comment_count: 22,
                        width: 22,
                        height: 22,
                        rate: 22,
                        download_count: 22,
                        play_count: 22,
                        share_count: 22,
                        whatsapp_share_count: 22,
                        forward_count: 22,
                        media_url: "string",
                        music: "string",
                        author: "string",
                        album: "string",
                        ratio: "string",
                        description: "string",
                        share_url: "string",
                        region: "string",
                        cover: "string",
                        dynamicCover: "string",
                    },
                ],
                profile_pic: "string",
                createTime: new Date(),
                privateAccount: false,
                verified: false,
                secret: false,
                tiktok_nickname: "string",
                bio_description: "string",
            },
            birthday: new Date(),
            birthday_lastupdate: new Date(),
            age: 11,
            job: "string",
            name: "name1",
            surname: "surname1",
            score: 11,
            email: "user1@email.com",
            gender: "male",
            // profile_complete: Boolean,
            school_type: "string",
            school_name: "string",
            city: "city1",
            country: "Turkiye",
            language: "Turkish",
            money: {
                paparaAccountNo: 111111,
                current: 22,
                currency: "TL",
                // exchanges: MoneyExchangeItemUser[],
                city: "Gaziantep",
                county: "string",
                name: "Serkan",
                surname: "Demir",
                id: "paparaID",
            },
            hobbies: ["string"],
            sharing_type: "string",
            last_login: new Date(),
            applications_update: new Date(),
            // hasNotificationPermission: Boolean,
            onesignal_pushToken: "string",
            onesignal_userId: "string",
            currency: "string",
            // password: Number,
            passwordTime: new Date(),
            // verification: Boolean,
            // denied_verification: Boolean,
            verification_last_action: new Date(),
            // deleted: Boolean,
            // address: UserAddress,
            deviceInfo: "Vestel Venüs",
        },
    },

    // User 2
    {
        userDoc: {
            phone: "0542",
            firebase_id: "string",
            notification_permission: false,
            notification_token: "string",
            insta: {
                last_scrape: new Date(),
                id: "string",
                access_token: "string",
                username: "username2",
                full_name: "igFullName2",
                biography: "user2's biography",
                profile_pic:
                    "https://images.pexels.com/photos/287240/pexels-photo-287240.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                followers: 22,
                following: 22,
                post_number: 22,
                average_like: 22,
                shared_posts: [
                    {
                        media_url: "string",
                        like_count: 22,
                        comment_count: 22,
                        // description: String,
                        // location: {
                        //     name: String,
                        //     address: String,
                        //     city: String,
                        //     lng: Number,
                        //     lat: Number,
                        // },
                        face_details: "any",
                        moderation_labels: "any",
                    },
                    {
                        media_url: "string",
                        like_count: 22,
                        comment_count: 22,
                        // description: String,
                        // location: {
                        //     name: String,
                        //     address: String,
                        //     city: String,
                        //     lng: Number,
                        //     lat: Number,
                        // },
                        face_details: "any",
                        moderation_labels: "any",
                    },
                ],
                keywords: "any",
            },
            tiktok: {
                tiktok_last_scrape: new Date(),
                // tiktok_average_like: Number,
                // tiktok_engagement_rate: Number,
                tiktok_access_token: "string",
                tiktok_refresh_token: "string",
                open_id: "string",
                refresh_expires_in: "string",
                log_id: "string",
                union_id: "string",
                username: "tiktokUsername2",
                last_scrape: new Date(),
                followers: 22,
                following: 22,
                hearts: 22,
                country: "string",
                videos: [
                    {
                        like_count: 22,
                        comment_count: 22,
                        width: 22,
                        height: 22,
                        rate: 22,
                        download_count: 22,
                        play_count: 22,
                        share_count: 22,
                        whatsapp_share_count: 22,
                        forward_count: 22,
                        media_url: "string",
                        music: "string",
                        author: "string",
                        album: "string",
                        ratio: "string",
                        description: "string",
                        share_url: "string",
                        region: "string",
                        cover: "string",
                        dynamicCover: "string",
                    },
                    {
                        like_count: 22,
                        comment_count: 22,
                        width: 22,
                        height: 22,
                        rate: 22,
                        download_count: 22,
                        play_count: 22,
                        share_count: 22,
                        whatsapp_share_count: 22,
                        forward_count: 22,
                        media_url: "string",
                        music: "string",
                        author: "string",
                        album: "string",
                        ratio: "string",
                        description: "string",
                        share_url: "string",
                        region: "string",
                        cover: "string",
                        dynamicCover: "string",
                    },
                ],
                profile_pic: "string",
                createTime: new Date(),
                privateAccount: false,
                verified: false,
                secret: false,
                tiktok_nickname: "string",
                bio_description: "string",
            },
            birthday: new Date(),
            birthday_lastupdate: new Date(),
            age: 22,
            job: "string",
            name: "name2",
            surname: "surname2",
            score: 11,
            email: "user2@email.com",
            gender: "female",
            // profile_complete: Boolean,
            school_type: "string",
            school_name: "string",
            city: "city2",
            country: "Turkiye",
            language: "Turkish",
            money: {
                paparaAccountNo: 222222,
                current: 44,
                currency: "TL",
                // exchanges: MoneyExchangeItemUser[],
                city: "Hatay",
                county: "string",
                name: "Furkan",
                surname: "Fidan",
                id: "paparaID2",
            },
            hobbies: ["string"],
            sharing_type: "string",
            last_login: new Date(),
            applications_update: new Date(),
            // hasNotificationPermission: Boolean,
            onesignal_pushToken: "string",
            onesignal_userId: "string",
            currency: "string",
            // password: Number,
            passwordTime: new Date(),
            // verification: Boolean,
            // denied_verification: Boolean,
            verification_last_action: new Date(),
            // deleted: Boolean,
            // address: UserAddress,
            deviceInfo: "Vestel Venüs2",
        },
    },

    // User 3
    {
        userDoc: {
            phone: "0543",
            firebase_id: "string",
            notification_permission: false,
            notification_token: "string",
            insta: {
                last_scrape: new Date(),
                id: "string",
                access_token: "string",
                username: "username3",
                full_name: "igFullName3",
                biography: "user3's biography",
                profile_pic:
                    "https://images.pexels.com/photos/848573/pexels-photo-848573.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                followers: 33,
                following: 33,
                post_number: 33,
                average_like: 33,
                shared_posts: [
                    {
                        media_url: "string",
                        like_count: 22,
                        comment_count: 22,
                        // description: String,
                        // location: {
                        //     name: String,
                        //     address: String,
                        //     city: String,
                        //     lng: Number,
                        //     lat: Number,
                        // },
                        face_details: "any",
                        moderation_labels: "any",
                    },

                    {
                        media_url: "string",
                        like_count: 22,
                        comment_count: 22,
                        // description: String,
                        // location: {
                        //     name: String,
                        //     address: String,
                        //     city: String,
                        //     lng: Number,
                        //     lat: Number,
                        // },
                        face_details: "any",
                        moderation_labels: "any",
                    },

                    {
                        media_url: "string",
                        like_count: 22,
                        comment_count: 22,
                        // description: String,
                        // location: {
                        //     name: String,
                        //     address: String,
                        //     city: String,
                        //     lng: Number,
                        //     lat: Number,
                        // },
                        face_details: "any",
                        moderation_labels: "any",
                    },
                ],
                keywords: "any",
            },
            tiktok: {
                tiktok_last_scrape: new Date(),
                // tiktok_average_like: Number,
                // tiktok_engagement_rate: Number,
                tiktok_access_token: "string",
                tiktok_refresh_token: "string",
                open_id: "string",
                refresh_expires_in: "string",
                log_id: "string",
                union_id: "string",
                username: "tiktokUsername3",
                last_scrape: new Date(),
                followers: 33,
                following: 33,
                hearts: 33,
                country: "string",
                videos: [
                    {
                        like_count: 22,
                        comment_count: 22,
                        width: 22,
                        height: 22,
                        rate: 22,
                        download_count: 22,
                        play_count: 22,
                        share_count: 22,
                        whatsapp_share_count: 22,
                        forward_count: 22,
                        media_url: "string",
                        music: "string",
                        author: "string",
                        album: "string",
                        ratio: "string",
                        description: "string",
                        share_url: "string",
                        region: "string",
                        cover: "string",
                        dynamicCover: "string",
                    },

                    {
                        like_count: 22,
                        comment_count: 22,
                        width: 22,
                        height: 22,
                        rate: 22,
                        download_count: 22,
                        play_count: 22,
                        share_count: 22,
                        whatsapp_share_count: 22,
                        forward_count: 22,
                        media_url: "string",
                        music: "string",
                        author: "string",
                        album: "string",
                        ratio: "string",
                        description: "string",
                        share_url: "string",
                        region: "string",
                        cover: "string",
                        dynamicCover: "string",
                    },

                    {
                        like_count: 22,
                        comment_count: 22,
                        width: 22,
                        height: 22,
                        rate: 22,
                        download_count: 22,
                        play_count: 22,
                        share_count: 22,
                        whatsapp_share_count: 22,
                        forward_count: 22,
                        media_url: "string",
                        music: "string",
                        author: "string",
                        album: "string",
                        ratio: "string",
                        description: "string",
                        share_url: "string",
                        region: "string",
                        cover: "string",
                        dynamicCover: "string",
                    },
                ],
                profile_pic: "string",
                createTime: new Date(),
                privateAccount: false,
                verified: false,
                secret: false,
                tiktok_nickname: "string",
                bio_description: "string",
            },
            birthday: new Date(),
            birthday_lastupdate: new Date(),
            age: 33,
            job: "string",
            name: "name3",
            surname: "surname3",
            score: 11,
            email: "user3@email.com",
            gender: "male",
            // profile_complete: Boolean,
            school_type: "string",
            school_name: "string",
            city: "city3",
            country: "Turkiye",
            language: "Turkish",
            money: {
                paparaAccountNo: 66666,
                current: 66,
                currency: "TL",
                // exchanges: MoneyExchangeItemUser[],
                city: "Bursa",
                county: "string",
                name: "İbo",
                surname: "Kardan",
                id: "paparaID3",
            },
            hobbies: ["string"],
            sharing_type: "string",
            last_login: new Date(),
            applications_update: new Date(),
            // hasNotificationPermission: Boolean,
            onesignal_pushToken: "string",
            onesignal_userId: "string",
            currency: "string",
            // password: Number,
            passwordTime: new Date(),
            // verification: Boolean,
            // denied_verification: Boolean,
            verification_last_action: new Date(),
            // deleted: Boolean,
            // address: UserAddress,
            deviceInfo: "Vestel Venüs V3",
        },
    },
];
